#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Bank-Fubon-TW
version:      0.01
version_from: lib/Finance/Bank/Fubon/TW.pm
installdirs:  site
requires:
    WWW::Mechanize:                0.39
    Crypt::SSLeay:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
